wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.14
    start_time: 1719001502.254153
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.14
      5: 0.13.11
      8:
      - 5
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 4
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: models/detect/yolov9-c.yaml
close_mosaic:
  desc: null
  value: 0
cos_lr:
  desc: null
  value: false
data:
  desc: null
  value: SailbotVT-4/data.yaml
device:
  desc: null
  value: cuda:0
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 4
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
fixed_lr:
  desc: null
  value: false
flat_cos_lr:
  desc: null
  value: false
freeze:
  desc: null
  value:
  - 10
hyp:
  desc: null
  value:
    anchor_t: 5.0
    box: 2.5
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    dfl: 1.0
    fl_gamma: 0.0
    fliplr: 0.0
    flipud: 0.0
    hsv_h: 0.0
    hsv_s: 0.0
    hsv_v: 0.0
    iou_t: 0.2
    lr0: 0.003
    lrf: 0.001
    mixup: 0.0
    momentum: 0.937
    mosaic: 0
    obj: 0.7
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.0
    shear: 0.0
    translate: 0.0
    warmup_bias_lr: 0.01
    warmup_epochs: 1.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
local_rank:
  desc: null
  value: -1
min_items:
  desc: null
  value: 0
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
noplots:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/exp49
save_period:
  desc: null
  value: -1
seed:
  desc: null
  value: 0
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: weights/yolov9-c.pt
workers:
  desc: null
  value: 8
